<?php
/**
 * Created by PhpStorm.
 * User: fruit
 * Date: 1/22/2019
 * Time: 3:24 PM
 */

namespace App\Http\Controllers;


use App\Question;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    protected $question;
    protected $rules = [];
    const DIRECTORY = 'files/questions';
    public function __construct(Question $question)
    {
        $this->question = $question;
        parent::__construct($question, $this->rules);
    }
    public function getByTutorial($id)
    {
        return $this->question::where('tutorial_id', $id)->get(); // TODO: Change the autogenerated stub
    }

    public function add(Request $request)
    {
        $questions = $request->input('questions');
        if ($questions) {
            return array_map(function ($q, $i) use ($request) {
                $q['author_id'] = app()->session_id;
                $q = $this->question::create($q);
                $file = $request->file("file$i");
                if ($file) {
                    $name = generateFileName(QuestionController::DIRECTORY, $file->extension());
                    $q->file()->create(['path' => $name]);
                    $file->move(QuestionController::DIRECTORY.'/', $name);
                }
                return $q;
            }, $questions, array_keys($questions));
        }
         else {
             $request['author_id'] = app()->session_id;
             $q = parent::add($request);
             $file = $request->file('file');
             $name = generateFileName(QuestionController::DIRECTORY, $file->extension());
             $q->file()->create(['path' => $name]);
             $file->move(QuestionController::DIRECTORY.'/', $name);
             return $q;
         }
    }

    public function deleteMany (Request $request) {
        return response()->json($this->question::whereIn('id', $request->input('ids', []))->delete());
    }

}