<?php
/**
 * Created by PhpStorm.
 * User: fruit
 * Date: 1/22/2019
 * Time: 3:24 PM
 */

namespace App\Http\Controllers;


use App\Question;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    protected $question;
    protected $rules = [];
    public function __construct(Question $question)
    {
        $this->question = $question;
        parent::__construct($question, $this->rules);
    }
    public function getByTutorial($id)
    {
        return $this->question::where('tutorial_id', $id)->get(); // TODO: Change the autogenerated stub
    }

    public function add(Request $request)
    {
        if ($request->input('questions')) {
            return array_map(function ($q) {
              return $this->question::create($q);
            }, $request->input('questions'));
        }
         else {
             return parent::add($request); // TODO: Change the autogenerated stub
         }
    }

    public function verify(Request $request) {
        $this->question::whereIn('id', $request->input('ids', []))->update(['verified' => true]);
    }
}